// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace mygame
{
	public class JsonHelper
	{
		public JsonHelper ()
		{
		}

		public static LitJson.JsonData LoadJsonFile(string file)
		{
			LitJson.JsonData data = null;
			
			TextAsset textAsset = Resources.Load<TextAsset>(file);
			if(textAsset == null)
			{
				Debug.LogError("Failed to load file " + file);
				return data;
			}
			
			try
			{
				data = LitJson.JsonMapper.ToObject(textAsset.text);
			}
			catch(System.Exception e)
			{
				Debug.LogError("Failed to parse json file " + file + ", exception: " + e.ToString());
			}
			
			return data;
		}
	}
}

