// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

namespace gamedata
{
	public class LevelData
	{
		public string 	prefab;
		public Vector2 	position;
		public float 	velocity;
		public float 	accelerate;
		public float 	rotation;

		public LevelData (LitJson.JsonData data)
		{
			prefab = (string)data["prefab"];

			LitJson.JsonData jposition = data["position"];
			position = new Vector2(
				(float)jposition[0],
				(float)jposition[1]
				);
			velocity = (float)data["velocity"];
			accelerate = (float)data["accelerate"];
			rotation = (float)data["rotation"];
		}
	}

	public class LevelWaveData
	{
		public LevelData []datas;

		public LevelWaveData(LitJson.JsonData data)
		{
			datas = new LevelData[data.Count];
			for(int i = 0; i < data.Count; ++i)
			{
				datas[i] = new LevelData(data[i]);
			}
		}
	}

	public class LevelDataMgr
	{
		private LevelWaveData []datas;

		public int Count{ get{ return datas.Length;} }

		public LevelDataMgr(LitJson.JsonData data)
		{
			datas = new LevelWaveData[data.Count];
			for(int i = 0; i < data.Count; ++i)
			{
				datas[i] = new LevelWaveData(data[i]);
			}
		}

		public LevelWaveData getWaveData(int waveIndex)
		{
			return datas[waveIndex];
		}
	}
}

